Fix moe build error due to using removeIf of MutableList class
Changes include
- downgraded build tool to 23.0.1 and sdk level to 20
- change gradle build to 2.2.3 which is gradle version 2.14.1
- integrate robovm 2.3.0 with the project but not currently used (it is
  for comparison when we finish the game to compare build from moe-ios
  i.e. build size etc)
- fixed build error of moe regarding to NoClassDefFoundError. See bug
  report to multi-os on github at
  https://github.com/multi-os-engine/multi-os-engine/issues/114 for more
  detail.

Now the game is buildable and runnable on iOS device.